sudo: false
language: php
php:
  - 5.5

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g bower gulp
  - npm install
  - bower install
  - gulp --production

script:
  - gulp --production
