version: 2.1

job-template: &job-template
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "composer.json" }}
            - dependencies-v1- 
      - run: composer install -n && composer test
      - save_cache:
          key: dependencies-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: yarn install && yarn run test && yarn run build:production
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build-php73:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    <<: *job-template
  build-php72:
    docker:
      - image: circleci/php:7.2-stretch-node-browsers
    <<: *job-template
  build-php71:
    docker:
      - image: circleci/php:7.1-stretch-node-browsers
    <<: *job-template

workflows:
  version: 2
  build:
    jobs:
      - build-php73
      - build-php72
      - build-php71
